#!/bin/bash
#
# this script creates a programming language script in a indicated dir.

usage() {
    SCRIPT_NAME="$(echo ${0} | awk -F '/' '{print $NF}')"
    echo "Usage: ${SCRIPT_NAME} FILENAME" >&2
    exit 1 
}

if [[ "${#}" -eq 0 ]];then
    usage
fi

NAME=${1}
PURE_NAME="$(echo $NAME | cut -d '.' -f 1)"
SUFFIX="$(echo $NAME | cut -d '.' -f 2)"
ADDRESS="/home/aes/"
if [[ "$SUFFIX" == 'cpp' ]];then
    cd "${ADDRESS}cpp"
elif [[ "$SUFFIX" == 'py' ]];then
    cd "${ADDRESS}python"
fi
mkdir $PURE_NAME
cd $PURE_NAME
vim ${NAME}
